### ISSUE TITLE
Are personal assets automatically supported?

### ISSUE THREAD

**Issue by fiatjaf** [0xfe/lumen#1]
For example, if I there are account alias for `joe` and `mary`, can I do

```
lumen balance joe USD:mary
```

to check how much USD `mary` owes to `bob`?

If not, what would it take to support it? What about the syntax, is `USD:mary` good enough? Would the same work with `USD:GC7BE5UFOO3BFHMNS6G66ANMLP4K22KIIIZAY6L6X67RWQA5GVHNBVNG`, for example?

**Comment by 0xfe** [comment]
Not sure I understand your question -- Stellar has no notion of "owing" assets.

If you mean a credit asset issued by Mary, then you can do this:

```sh
lumen asset set USD-mary mary --code USD
lumen balance joe USD
```

**Comment by fiatjaf** [comment]
Disconsidering the notion of owing assets, don't you think there could be an easy way to reference assets issued by other accounts from their aliases, instead of having to create aliases for the assets themselves?

**Comment by 0xfe** [comment]
Yeah, that sounds like a good idea. I like the `CODE:issuer` syntax -- I'll work on it.

**Comment by 0xfe** [comment]
Okay this works now and pushed to release v0.3.3. You can do:

```sh
# Directly
lumen balance joe USD:GDHFGIXGCXS2JYJYNF6LSXJOHACHFV7BHXNEERXUMBIWRJYGDEMF4VZ3

# With an account alias
lumen account set citibank GDHFGIXGCXS2JYJYNF6LSXJOHACHFV7BHXNEERXUMBIWRJYGDEMF4VZ3
lumen balance joe USD:citibank

# With a federated address
lumen balance joe USD:issuer*chase.com
```

Thanks for the suggestion!
