### ISSUE TITLE
Connect to bridge server

### ISSUE THREAD

**Issue by ark1** [0xfe/lumen#2]
Hi 
First of all much thanks for building this tool. By default Lumen sends payments directly to Horizon TestNet. Please advise on how you would connect to an anchor stellar bridge server for transaction submissions. eg. send payment to BOB in Lumen which submits transaction to Bridge, which can process federation or compliance then submits transaction to Horizon.

Please let me know if I am missing anything.
Thank You

**Comment by 0xfe** [comment]
You can use lumen to connect to custom horizon servers, but not to bridge servers (which use a custom protocol that I'm not sure is consistent yet.)
