### ISSUE TITLE
Missing lumen-config-test.yml 

### ISSUE THREAD

**Issue by ark1** [0xfe/lumen#3]
HI Mohit
Searched everywhere and I cant locate the lumen-config file. Also is it possible to set  config network to custom?

**Comment by 0xfe** [comment]
Hi,

Take a look at https://github.com/0xfe/hacking-stellar/blob/master/6-debugging.md for how to use a custom network.

Mo.

**Comment by 0xfe** [comment]
Not sure what config file you're looking for, but lumen automatically creates a `.lumen-data.yml` in your home directory where it stores its configuration.
